'use client';
import {useMemo,useState} from 'react';
const money=(n:number)=>Number(n||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
async function post(url:string,data:any){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)alert((await r.json()).error||'Error');else location.reload()}
export default function App({initial}:any){const [amount,setAmount]=useState(10000);const [pct,setPct]=useState('ลงทุน:40,หนี้:30,เงินเก็บ:20,ใช้จ่าย:10');const totalAccounts=initial.accounts.reduce((s:any,a:any)=>s+a.balance,0);const totalAssets=initial.assets.reduce((s:any,a:any)=>s+a.value,0);const totalDebt=initial.debts.reduce((s:any,d:any)=>s+(d.total-d.paid),0);const netWorth=totalAccounts+totalAssets-totalDebt;const savingRate=initial.splits.length?Math.round(((initial.splits[0].items||[]).filter((i:any)=>/เก็บ|ลงทุน/i.test(i.name)).reduce((s:number,i:any)=>s+i.value,0)/initial.splits[0].amount)*100):0;const score=Math.max(0,Math.min(100,50+(savingRate||0)-Math.round(totalDebt/Math.max(totalAccounts+totalAssets,1)*30)));
const items=useMemo(()=>pct.split(',').map(x=>{const [name,p]=x.split(':');return {name:name?.trim(),percent:Number(p||0),value:amount*Number(p||0)/100}}).filter(x=>x.name),[pct,amount]);
return <><div className="nav"><div><div className="brand">MoneyFlow Pro</div><div className="muted">สวัสดี {initial.user.name}</div></div><div className="row"><form action="/api/auth/logout" method="post"><button className="btn2">Logout</button></form></div></div><div className="wrap"><div className="grid"><div className="card"><div className="muted">Net Worth</div><div className="big">฿{money(netWorth)}</div></div><div className="card"><div className="muted">Financial Score</div><div className="big">{score}/100</div><progress value={score} max="100"/></div><div className="card"><div className="muted">Accounts</div><div className="big">฿{money(totalAccounts)}</div></div><div className="card"><div className="muted">Debt Remaining</div><div className="big">฿{money(totalDebt)}</div></div></div>
<div className="grid" style={{marginTop:14}}><section className="card"><h2>แบ่งเงิน</h2><label>ยอดเงิน</label><input type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><label>สูตรแบ่งเงิน</label><input value={pct} onChange={e=>setPct(e.target.value)} /><p className="muted">ตัวอย่าง: ลงทุน:40,หนี้:30,เงินเก็บ:20,ใช้จ่าย:10</p>{items.map((i:any)=><div className="between" key={i.name}><span>{i.name} {i.percent}%</span><b>฿{money(i.value)}</b></div>)}<button className="btn" onClick={()=>post('/api/splits',{amount,planName:'Quick Split',items})}>บันทึก History</button></section>
<section className="card"><h2>เพิ่ม Account + QR URL</h2><input id="an" placeholder="SCB / KBank / Cash"/><input id="ab" type="number" placeholder="ยอดเงิน"/><input id="aq" placeholder="QR Image URL (ใส่ลิงก์รูป QR)"/><button className="btn" onClick={()=>post('/api/accounts',{name:(document.getElementById('an') as HTMLInputElement).value,balance:Number((document.getElementById('ab') as HTMLInputElement).value),qrUrl:(document.getElementById('aq') as HTMLInputElement).value})}>เพิ่มบัญชี</button></section>
<section className="card"><h2>Budget รายเดือน</h2><input id="bm" placeholder="2026-07"/><input id="bc" placeholder="อาหาร / น้ำมัน"/><input id="bl" type="number" placeholder="งบ"/><button className="btn" onClick={()=>post('/api/budgets',{month:(document.getElementById('bm') as HTMLInputElement).value,category:(document.getElementById('bc') as HTMLInputElement).value,limit:Number((document.getElementById('bl') as HTMLInputElement).value)})}>เพิ่ม Budget</button></section>
<section className="card"><h2>Goals</h2><input id="gn" placeholder="เงินฉุกเฉิน / รถ / บ้าน"/><input id="gt" type="number" placeholder="เป้าหมาย"/><input id="gc" type="number" placeholder="มีแล้ว"/><button className="btn" onClick={()=>post('/api/goals',{name:(document.getElementById('gn') as HTMLInputElement).value,target:Number((document.getElementById('gt') as HTMLInputElement).value),current:Number((document.getElementById('gc') as HTMLInputElement).value)})}>เพิ่ม Goal</button></section>
<section className="card"><h2>Debt</h2><input id="dn" placeholder="ค่ารถ / บัตรเครดิต"/><input id="dt" type="number" placeholder="ยอดหนี้ทั้งหมด"/><input id="dp" type="number" placeholder="จ่ายแล้ว"/><button className="btn" onClick={()=>post('/api/debts',{name:(document.getElementById('dn') as HTMLInputElement).value,total:Number((document.getElementById('dt') as HTMLInputElement).value),paid:Number((document.getElementById('dp') as HTMLInputElement).value)})}>เพิ่มหนี้</button></section>
<section className="card"><h2>Recurring</h2><input id="rn" placeholder="เงินเดือน / ค่าเช่า"/><select id="rk"><option value="income">รายรับ</option><option value="expense">รายจ่าย</option></select><input id="ra" type="number" placeholder="จำนวนเงิน"/><button className="btn" onClick={()=>post('/api/recurring',{name:(document.getElementById('rn') as HTMLInputElement).value,kind:(document.getElementById('rk') as HTMLSelectElement).value,amount:Number((document.getElementById('ra') as HTMLInputElement).value),frequency:'monthly'})}>เพิ่มประจำ</button></section></div>
<h2>Accounts</h2><div className="grid">{initial.accounts.map((a:any)=><div className="card" key={a.id}><b>{a.name}</b><div>฿{money(a.balance)}</div>{a.qrUrl&&<img className="qr" src={a.qrUrl}/>}</div>)}</div><h2>History</h2><div className="card"><table className="table"><tbody>{initial.splits.map((s:any)=><tr key={s.id}><td>{new Date(s.createdAt).toLocaleString('th-TH')}</td><td>{s.planName}</td><td>฿{money(s.amount)}</td><td>{s.status}</td></tr>)}</tbody></table></div><p style={{marginTop:20}}><a className="link" href="/api/backup">Download Backup JSON</a></p></div></>}
